### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by syphernl** [JpEncausse/WSRNodeJS#2]
Currently this project seems to have a lot of hardcoded French sentences in it, which makes it very hard to use for people who do not speak French. Perhaps it would be possible to move all these strings to a translation system and allow people to translate / provide translations for other languages. 

This would also open the possibility for the project to expand to more than just French-speaking countries.

**Comment by JpEncausse** [comment]
French sentences should only be XML French Grammar and linked plugns.

You could copy any XML grammar and translate sentences in you language. https://github.com/JpEncausse/SARAH-Documentation/wiki/Voice-Recognition#setup-other-language

For JS side, plugins mostly answer in french and query french site, API, etc ... because they are developped by french community. It should be really easy to rewrite plugin for a given language (but there is more than juste a resource bundle)
